=== VyacheslavGorb/EpamXML/src/main/resources/files/vouchers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.com/tourist-vouchers"
        xmlns:tns="http://www.example.com/tourist-vouchers" elementFormDefault="qualified">

    <element name="tourist-vouchers" type="tns:TouristVouchers"/>

    <complexType name="TouristVouchers">
        <sequence>
            <element ref="tns:voucher" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Voucher">
        <sequence>
            <element name="country" type="tns:Countries"/>
            <element name="departure-date-time" type="dateTime"/>
            <element name="arrival-date-time" type="dateTime"/>
            <element name="transport-type" type="tns:Transport"/>
            <element name="hotel" type="tns:Hotel"/>
            <element name="cost" type="positiveInteger"/>
        </sequence>
        <attribute name="id" type="ID" use="required"/>
        <attribute name="web-site" type="tns:Link" use="optional" default="https://www.tour.com"/>
    </complexType>

    <complexType name="PilgrimageVoucher">
        <complexContent>
            <extension base="tns:Voucher">
                <sequence>
                    <element name="pilgrimage-passport-required" type="boolean"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="BeachVacationVoucher">
        <complexContent>
            <extension base="tns:Voucher">
                <sequence>
                    <element name="distance-to-beach" type="tns:DistanceToBeach"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="DistanceToBeach">
        <restriction base="positiveInteger">
            <minInclusive value="10"/>
            <maxInclusive value="5000"/>
        </restriction>
    </simpleType>

    <complexType name="Hotel">
        <sequence>
            <element name="stars" type="tns:Stars"/>
            <element name="food" type="tns:FoodType"/>
            <element name="place-count" type="tns:PlaceCount"/>
            <element name="air-conditioning" type="boolean"/>
            <element name="tv" type="boolean"/>
        </sequence>
    </complexType>

    <simpleType name="Link">
        <restriction base="string">
            <pattern value="(https|http)?://[^\s]+"/>
        </restriction>
    </simpleType>

    <simpleType name="PlaceCount">
        <restriction base="positiveInteger">
            <minInclusive value="1"/>
            <maxInclusive value="10"/>
        </restriction>
    </simpleType>

    <simpleType name="FoodType">
        <restriction base="string">
            <enumeration value="HB"/>
            <enumeration value="BB"/>
            <enumeration value="AL"/>
            <enumeration value="NO"/>
        </restriction>
    </simpleType>

    <simpleType name="Stars">
        <restriction base="positiveInteger">
            <minInclusive value="1"/>
            <maxInclusive value="7"/>
        </restriction>
    </simpleType>

    <simpleType name="Transport">
        <restriction base="string">
            <enumeration value="Auto"/>
            <enumeration value="Plane"/>
            <enumeration value="Train"/>
            <enumeration value="Ship"/>
        </restriction>
    </simpleType>

    <simpleType name="Countries">
        <restriction base="string">
            <enumeration value="USA"/>
            <enumeration value="UAE"/>
            <enumeration value="Russia"/>
            <enumeration value="Egypt"/>
        </restriction>
    </simpleType>

    <element name="voucher" type="tns:Voucher" abstract="true"/>
    <element name="beach-vacation-voucher" type="tns:BeachVacationVoucher" substitutionGroup="tns:voucher"/>
    <element name="pilgrimage-voucher" type="tns:PilgrimageVoucher" substitutionGroup="tns:voucher"/>
</schema>

=== VyacheslavGorb/EpamXML/src/main/resources/files/vouchers.xml
<?xml version="1.0" encoding="UTF-8"?>
<tourist-vouchers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xmlns="http://www.example.com/tourist-vouchers"
                  xsi:schemaLocation="http://www.example.com/tourist-vouchers vouchers.xsd">

    <beach-vacation-voucher id="id1" web-site="https://www.tour1.com">
        <country>USA</country>
        <departure-date-time>2001-11-17T06:00:00</departure-date-time>
        <arrival-date-time>2001-12-03T06:00:00</arrival-date-time>
        <transport-type>Auto</transport-type>
        <hotel>
            <stars>5</stars>
            <food>AL</food>
            <place-count>4</place-count>
            <air-conditioning>true</air-conditioning>
            <tv>true</tv>
        </hotel>
        <cost>1232</cost>
        <distance-to-beach>400</distance-to-beach>
    </beach-vacation-voucher>

    <beach-vacation-voucher web-site="https://www.tour1.com" id="id2">
        <country>Egypt</country>
        <departure-date-time>2001-11-17T06:00:00</departure-date-time>
        <arrival-date-time>2001-12-03T06:00:00</arrival-date-time>
        <transport-type>Auto</transport-type>
        <hotel>
            <stars>5</stars>
            <food>AL</food>
            <place-count>4</place-count>
            <air-conditioning>true</air-conditioning>
            <tv>true</tv>
        </hotel>
        <cost>1232</cost>
        <distance-to-beach>400</distance-to-beach>
    </beach-vacation-voucher>

    <beach-vacation-voucher id="id3">
        <country>Russia</country>
        <departure-date-time>2001-11-18T06:20:00</departure-date-time>
        <arrival-date-time>2001-12-03T06:00:00</arrival-date-time>
        <transport-type>Plane</transport-type>
        <hotel>
            <stars>7</stars>
            <food>HB</food>
            <place-count>5</place-count>
            <air-conditioning>true</air-conditioning>
            <tv>false</tv>
        </hotel>
        <cost>123542</cost>
        <distance-to-beach>2342</distance-to-beach>
    </beach-vacation-voucher>

    <beach-vacation-voucher id="id4">
        <country>UAE</country>
        <departure-date-time>2005-11-18T06:20:00</departure-date-time>
        <arrival-date-time>2005-12-18T06:20:00</arrival-date-time>
        <transport-type>Train</transport-type>
        <hotel>
            <stars>2</stars>
            <food>BB</food>
            <place-count>3</place-count>
            <air-conditioning>false</air-conditioning>
            <tv>true</tv>
        </hotel>
        <cost>432</cost>
        <distance-to-beach>230</distance-to-beach>
    </beach-vacation-voucher>

    <beach-vacation-voucher id="id5">
        <country>USA</country>
        <departure-date-time>2005-11-18T06:20:00</departure-date-time>
        <arrival-date-time>2005-12-18T06:20:00</arrival-date-time>
        <transport-type>Plane</transport-type>
        <hotel>
            <stars>5</stars>
            <food>HB</food>
            <place-count>6</place-count>
            <air-conditioning>true</air-conditioning>
            <tv>true</tv>
        </hotel>
        <cost>434</cost>
        <distance-to-beach>1233</distance-to-beach>
    </beach-vacation-voucher>

    <beach-vacation-voucher id="id6">
        <country>Russia</country>
        <departure-date-time>2005-11-18T06:20:00</departure-date-time>
        <arrival-date-time>2005-12-18T06:20:00</arrival-date-time>
        <transport-type>Auto</transport-type>
        <hotel>
            <stars>2</stars>
            <food>AL</food>
            <place-count>1</place-count>
            <air-conditioning>true</air-conditioning>
            <tv>true</tv>
        </hotel>
        <cost>1000</cost>
        <distance-to-beach>30</distance-to-beach>
    </beach-vacation-voucher>

    <beach-vacation-voucher id="id7">
        <country>Egypt</country>
        <departure-date-time>2005-11-18T06:20:00</departure-date-time>
        <arrival-date-time>2005-12-18T06:20:00</arrival-date-time>
        <transport-type>Auto</transport-type>
        <hotel>
            <stars>4</stars>
            <food>BB</food>
            <place-count>4</place-count>
            <air-conditioning>false</air-conditioning>
            <tv>false</tv>
        </hotel>
        <cost>200</cost>
        <distance-to-beach>500</distance-to-beach>
    </beach-vacation-voucher>

    <beach-vacation-voucher id="id8">
        <country>Russia</country>
        <departure-date-time>2005-11-18T06:20:00</departure-date-time>
        <arrival-date-time>2005-12-18T06:20:00</arrival-date-time>
        <transport-type>Plane</transport-type>
        <hotel>
            <stars>3</stars>
            <food>BB</food>
            <place-count>3</place-count>
            <air-conditioning>false</air-conditioning>
            <tv>false</tv>
        </hotel>
        <cost>400</cost>
        <distance-to-beach>300</distance-to-beach>
    </beach-vacation-voucher>

    <pilgrimage-voucher id="id9">
        <country>Egypt</country>
        <departure-date-time>2005-11-18T06:20:00</departure-date-time>
        <arrival-date-time>2005-12-18T06:20:00</arrival-date-time>
        <transport-type>Plane</transport-type>
        <hotel>
            <stars>3</stars>
            <food>NO</food>
            <place-count>2</place-count>
            <air-conditioning>false</air-conditioning>
            <tv>false</tv>
        </hotel>
        <cost>1000</cost>
        <pilgrimage-passport-required>true</pilgrimage-passport-required>
    </pilgrimage-voucher>

    <pilgrimage-voucher id="id10">
        <country>USA</country>
        <departure-date-time>2005-11-18T06:20:00</departure-date-time>
        <arrival-date-time>2005-12-18T06:20:00</arrival-date-time>
        <transport-type>Auto</transport-type>
        <hotel>
            <stars>4</stars>
            <food>AL</food>
            <place-count>3</place-count>
            <air-conditioning>false</air-conditioning>
            <tv>false</tv>
        </hotel>
        <cost>4000</cost>
        <pilgrimage-passport-required>true</pilgrimage-passport-required>
    </pilgrimage-voucher>

    <pilgrimage-voucher id="id11">
        <country>UAE</country>
        <departure-date-time>2005-11-18T06:20:00</departure-date-time>
        <arrival-date-time>2005-12-18T06:20:00</arrival-date-time>
        <transport-type>Plane</transport-type>
        <hotel>
            <stars>7</stars>
            <food>AL</food>
            <place-count>3</place-count>
            <air-conditioning>true</air-conditioning>
            <tv>true</tv>
        </hotel>
        <cost>7000</cost>
        <pilgrimage-passport-required>true</pilgrimage-passport-required>
    </pilgrimage-voucher>

    <pilgrimage-voucher id="id12">
        <country>UAE</country>
        <departure-date-time>2005-11-18T06:20:00</departure-date-time>
        <arrival-date-time>2005-12-18T06:20:00</arrival-date-time>
        <transport-type>Auto</transport-type>
        <hotel>
            <stars>4</stars>
            <food>NO</food>
            <place-count>3</place-count>
            <air-conditioning>true</air-conditioning>
            <tv>true</tv>
        </hotel>
        <cost>3000</cost>
        <pilgrimage-passport-required>false</pilgrimage-passport-required>
    </pilgrimage-voucher>

    <pilgrimage-voucher id="id13">
        <country>UAE</country>
        <departure-date-time>2005-11-18T06:20:00</departure-date-time>
        <arrival-date-time>2005-12-18T06:20:00</arrival-date-time>
        <transport-type>Plane</transport-type>
        <hotel>
            <stars>1</stars>
            <food>NO</food>
            <place-count>1</place-count>
            <air-conditioning>false</air-conditioning>
            <tv>false</tv>
        </hotel>
        <cost>100</cost>
        <pilgrimage-passport-required>true</pilgrimage-passport-required>
    </pilgrimage-voucher>

    <pilgrimage-voucher id="id14">
        <country>Egypt</country>
        <departure-date-time>2005-11-18T06:20:00</departure-date-time>
        <arrival-date-time>2005-12-18T06:20:00</arrival-date-time>
        <transport-type>Train</transport-type>
        <hotel>
            <stars>4</stars>
            <food>AL</food>
            <place-count>2</place-count>
            <air-conditioning>true</air-conditioning>
            <tv>true</tv>
        </hotel>
        <cost>3000</cost>
        <pilgrimage-passport-required>true</pilgrimage-passport-required>
    </pilgrimage-voucher>

    <pilgrimage-voucher id="id15">
        <country>Russia</country>
        <departure-date-time>2005-11-18T06:20:00</departure-date-time>
        <arrival-date-time>2005-12-18T06:20:00</arrival-date-time>
        <transport-type>Plane</transport-type>
        <hotel>
            <stars>5</stars>
            <food>AL</food>
            <place-count>3</place-count>
            <air-conditioning>true</air-conditioning>
            <tv>true</tv>
        </hotel>
        <cost>1000</cost>
        <pilgrimage-passport-required>false</pilgrimage-passport-required>
    </pilgrimage-voucher>

    <pilgrimage-voucher id="id16">
        <country>UAE</country>
        <departure-date-time>2005-11-18T06:20:00</departure-date-time>
        <arrival-date-time>2005-12-18T06:20:00</arrival-date-time>
        <transport-type>Auto</transport-type>
        <hotel>
            <stars>6</stars>
            <food>AL</food>
            <place-count>2</place-count>
            <air-conditioning>true</air-conditioning>
            <tv>true</tv>
        </hotel>
        <cost>1800</cost>
        <pilgrimage-passport-required>true</pilgrimage-passport-required>
    </pilgrimage-voucher>


</tourist-vouchers>
